export const salesStrings = {
  companies: {
    breadcrumb: "Sales / Companies",
    title: "Companies",
    primaryAction: "New company",
  },
  board: {
    columnEmpty: "No companies here",
    contactsLabel: (count: number) => `${count} contact${count === 1 ? "" : "s"}`,
    pendingBadge: "Enriching",
    failedBadge: "Enrichment failed",
  },
  detail: {
    backLabel: "Back to pipeline",
    employeesLabel: "employees",
    contactsLabel: "contacts",
    infoPanel: {
      title: "Company details",
      industry: "Industry",
      employeeCount: "Employees",
      revenue: "Revenue",
      funding: "Total funding",
      lastFundingAt: "Last funding",
      growth6mo: "Growth (6 mo)",
      growth12mo: "Growth (12 mo)",
      growth24mo: "Growth (24 mo)",
      techStack: "Tech stack",
      deptHeadcount: "Headcount by department",
      enrichment: "Enrichment",
      empty: "—",
    },
    contactsPanel: {
      title: "Contacts",
      empty: "No contacts captured for this company yet.",
      verified: "Verified",
      touchpointsLabel: (count: number) => `${count} touchpoint${count === 1 ? "" : "s"}`,
    },
    emailGenerator: {
      title: "Draft an email",
      recipientLabel: "Who is this for?",
      recipientPlaceholder: "Select a contact",
      noContacts: "Add a contact for this company before drafting an email.",
      includeTouchpointsLabel: "Use their touchpoint notes",
      noTouchpoints: "No touchpoint notes on file for this contact.",
      includeStageLabel: "Mention current pipeline stage",
      instructionsLabel: "Custom instructions",
      instructionsPlaceholder: "e.g. keep it under 100 words, invite them to a demo call...",
      submit: "Generate draft",
      regenerate: "Regenerate",
      subjectLabel: "Subject",
      bodyLabel: "Body",
      logAction: "Log this draft as an activity",
      logged: "Logged to activity",
    },
    activityLog: {
      title: "Activity",
      placeholder: "Log a call, meeting, or update...",
      submit: "Add",
      empty: "No activity logged yet.",
    },
  },
} as const;
