export const eventsStrings = {
  events: {
    breadcrumb: "Events",
    title: "Events",
    metaLabels: {
      total: "events",
      upcoming: "upcoming",
      past: "past",
    },
    primaryAction: "New event",
  },
  emptyState: {
    title: "No events yet",
    description: "Create your first event to start capturing contacts at the booth.",
    cta: "Create an event",
  },
  groups: {
    upcoming: "Upcoming",
    past: "Past",
  },
  card: {
    eyebrow: "Event",
    contactsLabel: "contacts captured",
    companiesLabel: "companies discovered",
  },
  createEvent: {
    modalTitle: "Create event",
    nameLabel: "Name",
    namePlaceholder: "Event name",
    cityLabel: "City",
    cityPlaceholder: "City",
    startDateLabel: "Start date",
    endDateLabel: "End date",
    submit: "Create event",
  },
  eventDetail: {
    backLabel: "Events",
    deleteAction: "Delete",
  },
  captureContact: {
    title: "Capture attendee",
    emailLabel: "Work email",
    emailPlaceholder: "jane.doe@acme.com",
    emailError: "Enter a valid work email",
    roleLabel: "Role",
    rolePlaceholder: "e.g. VP of Engineering",
    noteLabel: "Conversation note",
    notePlaceholder: "What did you talk about at the booth?",
    submit: "Capture attendee",
    strength: {
      label: "Record strength",
      needEmail: "Add a valid work email to start extracting a record.",
      needName: "We couldn't extract a name — add one to the badge.",
      needCompany: "Add their company to enrich this record.",
      needRole: "Add their role to help sales gauge seniority.",
      needNote: "Add a note so sales remembers this conversation.",
      complete: "Great record — ready to hand off to sales.",
    },
    banner: {
      addedSuffix: "added to this event",
      resolvedTo: "Resolved to",
    },
    roster: {
      heading: "Captured",
      emptyTitle: "No one captured yet",
      emptyDescription: "Add the first person you meet using the form above.",
      columnAttendee: "Attendee",
      columnRole: "Role",
      columnCompany: "Company",
      columnCaptured: "Captured",
      removeAction: "Remove",
    },
  },
} as const;
